dist: trusty
sudo: required
addons:
  chrome: stable
language: java
install:
- wget -N http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip
  -P ~/
- unzip ~/chromedriver_linux64.zip -d ~/
- rm ~/chromedriver_linux64.zip
- sudo mv -f ~/chromedriver /usr/local/share/
- sudo chmod +x /usr/local/share/chromedriver
- sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
deploy:
  provider: heroku
  api_key:
    - secure: FJCRu8wHfA0TlN4O+2u1Zlp0XxgLq/FyJLyiGm90Sw8tYyY25pm3zCg9v9H3qU7zbJNQ29hm5UC6OQNQIeCxc42lW23epAIa+GpocZaUMBQPlRoK0T8BW3a/mnpNgFxT54v3LYaadAM6L1mzwyqf305E7F+dYlthQlcfIb3e1Xm1cEmqp2y35yQoOKZ+dYC37oThkL4fyFV1R16P2b8heeTGlkzRYt4WDKa1WXAGc2c73H2PScBAqJUCrZtd6HJlD3azNV8RL0DAsj2b/bLM1rgUZuuMWR5jt5nC9PGc31rS6CgdffHjKQe6Rs3dq1zE6PcajyWsP4hNSlOn4C1DSe/8tB7PJxndGfPp4K45p9rGQw6XCIewD+7g90rzf2YHnhcuZmAOjVQqk+74lqZ/Mn+GNJLz4ySCIYjLQVtLWhzPZ++E+w24/cnxuPiGdVu0UMs0LJueLaUabaNz7k5DobzThMrV2CNISf4P+USR4UV119iJr+8fBKx4FRxF4S1bh3dSr8k7596mKvDQMq1Wz/ZgRjop9cEkA34GqjjCBhWjdTxmcjxQb90YzEuVJRFjLEnu/bpai09N0DQLt5m2ESjfPk9RWodkzDe2511yKw0WsmLWrLEnKUTpwFgLvD+GSODyXKrDbIg0AfMGSF1C0zwFTQZ06PpgkGC6dRI6wQo=
  app: TicTacToe
