dist: trusty
sudo: required
addons:
  chrome: stable
language: java
deploy:
provider: heroku
app: hidden-dusk-82258
api_key:
  - secure: il4BG8o0JTkPqwhj63sNzanvai0STZAo5QDk6u8BZbubpk5O+YmWK6TnhKS7zBxyyYbgCmQM5y8ZzhvCo9hdnWgyOkRFFjkzqPEe2gF/rafQRS6/xdI0P7NChpnu4POIfzaZN1wNQ0iDMWOQJ5BECLLqaYEQfLAZa+Kqo5WQibgc6KrerxN7ZY8XyWMPka/D0Xk8ngRZkHxfGnZhFBLPTeA9i0N2rgd6AlgMVEaEtlpbKCogwDwTMzkJbT5jyz7SAdKDPVEkuZox1VWwP2seTJYZbGVwi31HKnBPvjtibh11mn64XOQmwQL3tupqnCFmuIcJ5rHeckbzncViQ6viYYivP5+OxWpMEBaQry3VYvEcbn5R5Gy+JvZDZ/qluCo8LeL3y/hDcZfzSXBqLKIDpceQNBFLsMN1o+bqo1KREzJV2nL4EEumr/cRTsSLfVGZ4rKBCmXxLKhj3fF+nmTh5MJOkGXoHVv+433Z+dPRwDdTm8Vg69BEja67m/kpyLDFM9TjMcuV+VPml82b1KeLTWXAl2zg76IOwbXLuqcPX289Xlw1q0LJxdOeDHbVSxSUUI0UeHnB5ISlPVSn+DqMwjiYgU51BzX5cMshXZu3+hvri+XFrZGbGmIdCgxbisWu4stPGPiObS9n39vQZx3p/OfAcP+61+Mq55ogLYgDT68=
before_install:
- google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 https://hidden-dusk-82258.herokuapp.com/ &
install: # Install ChromeDriver (64bits; replace 64 with 32 for 32bits).
  - wget -N http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3